### ISSUE TITLE
Some problems abort Flash

### ISSUE THREAD

**Issue by xbin-xu** [OpenPuya/PY32F002B_Firmware#2]
## `HAL_FLASH_Program` will cause HardFault when `DataAddr` is unaligned

Because of Cortex-M0+ not supporting unaligned access.

in the example `Projects/PY32F002B-STK/Example/FLASH/FLASH_PageEraseAndWrite`,
if the `DATA` address is unaligned (e.g., an odd address), a HardFault will
occur at `*(uint32_t *)dest = *src;`.
The call stack is: `APP_FlashProgram -> HAL_FLASH_Program -> FLASH_Program_Page`

I am wondering whether it should be pointed out in the HAL library's API.
That is, add a note that the address pointed to by `DataAddr` must be 4-byte
aligned. For example, add a comment or check if `DataAddr` is 4-byte aligned.

```c
// 1. Add comment
// @param  DataAddr Page Start Address, must by 4 byte aligned

// 2. Add assert or return HAL_ERROR, if DataAddr is not 4 byte aligned
assert_param(((uint32_t)(*((uint32_t **)&DataAddr)) % 4) == 0);
```

## By the way

1. Is the Makefile in the example auto-generated? I cannot use it directly in `bash/powershell`.
   I need to make the following changes:

    ```diff
    -BUILD_DIR = build\Project
    +BUILD_DIR = build/Project

    $(BUILD_DIR):
    -   mkdir $@
    +   mkdir -p $@
    ```

2. After defining `USE_FULL_ASSERT`, the following assert prevents writing to the last page of FLASH due to:

    ```c
    // #define IS_FLASH_NB_PAGES(__ADDRESS__, __VALUE__)      (((__ADDRESS__) >= (FLASH_BASE)) && ((__ADDRESS__ + (__VALUE__*FLASH_PAGE_SIZE)) <= (FLASH_BASE + FLASH_SIZE - 1UL)))
    assert_param(IS_FLASH_NB_PAGES(pEraseInit->PageAddress, pEraseInit->NbPages));
    ```

**Comment by HalfSweet** [comment]
First of all thank you very much for your issue!
Secondly I need to point out that for the `PY32F002B` series of MCUs, any operation on the flash must be “page” aligned, which should be 128 bytes at the moment.
![图片](https://github.com/user-attachments/assets/8ebbb45e-e469-4668-942e-8dc80ea316b1)

Thanks for the solution, but I'm afraid I can't merge it into the repository, because the repository only mirrors the official puya upstream code, and any changes made are not synchronized!

**Comment by xbin-xu** [comment]
Thank you for your response. I did not read the documentation carefully.
